version: 2.1

jobs:
  lint:
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile
  build:
    docker:
      - image: docker:20.10.16-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build --build-arg BUILD_ID=${CIRCLE_WORKFLOW_ID:0:7} -t site .
            docker save -o site.tar site
      - persist_to_workspace:
          root: .
          paths:
            - site.tar
  publish:
    docker:
      - image: docker:20.10.16-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Tag docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_LOGIN --password-stdin
            docker load -i site.tar
            docker tag site "$DOCKERHUB_LOGIN/$CIRCLE_PROJECT_REPONAME:${CIRCLE_WORKFLOW_ID:0:7}"
            docker push "$DOCKERHUB_LOGIN/$CIRCLE_PROJECT_REPONAME:${CIRCLE_WORKFLOW_ID:0:7}"
      - persist_to_workspace:
          root: .
          paths:
            - site.tar

workflows:
  default:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - publish:
          requires:
            - build
